import { Group } from './contact';

export const groupList: Group[] = [
/*  {
    groupimg: 'assets/images/profile/user.jpg',
    nom: 'sad',
    id: 'ID',
    contactadd: '795 Folsom Ave, Suite 600 San Francisco, NY, 10003',
    contactno: '(123) 456-7890',
    contactinstagram: '254',
    contactlinkedin: '54',
    contactfacebook: '154',
  },
  {
    groupimg: 'assets/images/profile/user.jpg',
    groupname: 'poor',
    groupid: 'ID',
    contactadd: '55 E 11th St #1OTH, Suite 600 New York, NY, 10003 ',
    contactno: '(212) 228-8403',
    contactinstagram: '150',
    contactlinkedin: '14',
    contactfacebook: '165',
  },
  {
    groupimg: 'assets/images/profile/user.jpg',
    groupname: 'happy',
    groupid: 'ID',
    contactadd: '36 W 138th St, San Francisco New York, NY, 10037',
    contactno: '(212) 234-0783',
    contactinstagram: '300',
    contactlinkedin: '65',
    contactfacebook: '130',
  },
  {
    groupimg: 'assets/images/profile/user.jpg',
    groupname: 'bored',
    groupid: 'ID',
    contactadd: '2289 5th Ave, Suite 600 San Francisco New York, NY, 10037',
    contactno: '(212) 456-8403',
    contactinstagram: '220',
    contactlinkedin: '38',
    contactfacebook: '178',
  },
  {
    groupimg: 'assets/images/profile/user.jpg',
    groupname: 'mad',
    groupid: 'ID',
    contactadd: '425 5th Ave, Suite 600 Francisco New York, NY, 10016',
    contactno: '(154) 456-8745',
    contactinstagram: '650',
    contactlinkedin: '150',
    contactfacebook: '195',
  },
  {
    groupimg: 'assets/images/profile/user.jpg',
    groupname: 'hungry',
    groupid: 'ID',
    contactadd: '17 Stuyvesant Walk, Suite 600 New York, NY, 10009',
    contactno: '(150) 784-7890',
    contactinstagram: '151',
    contactlinkedin: '29',
    contactfacebook: '160',
  },*/
];
